dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
- rm local_settings.py
deploy:
  provider: heroku
  app: antmaczam-decide-ci
  strategy: git
  api_key:
    secure: PBpW9ConDS4sp0/RoQBIcVZTVcRR32AGgU3Eih9CriZM26HPw2jFGIieBdS8uFfxO68O5dJwfYEqbU2Q9FTFfwV6SOEmlMTJB5Jo9ufCiN3ucYkG0ykhRceTtoxD3d4gomVPz+N4TOO8BGMcksiCs2By/1f/aFD3lq9WoUFPEGpk9qmtpRBiuOH/uwdJjCE2Jc0TPDGg3vHaOsPPz08TzCRQCt/bV8+xCniEsBKwiNXcbdn0OI5MdPQMiRl+i2Qnt9ucQBJugve29u5LbMkIhkMmps3SkqlK5oj5FWcwz8KzFXIHN+U1k+FvnectLUxWnWMzFwKfbuKvPsR67dVL9F5RtxLLVST2A8Io6hdgNfpXYib4kxHO5PuVxzNc/PTUU2PthfiNGkkFLpF9u2lFPICh4vsgz2zQeg/KAQgzMSPI9dnf1VOT4NU3hSaAR/GGII5H1Pl5dO9aGRPzXqde5rbTdEpIt6CXjpajmR4OTl009Re7ZD6t9KgoieFZoOpf99ePT4edKunpt2GM3lVpq1ClX/x+996Inv7fMXLTGMRJyF0puK+0g6gnT+qwSHF/8hSuodnVxXnty9yrEsg/9lqLaHiDHD+wBSMI4wMhxW34UYaCCNAIJdStQNGyeiX4cZCRpU4OpzeYkZHnTH4w3uDPX3ieZLFvhu4thAY+9Fk=
